spring:
  application:
    name: notification-service

  mail:
    properties:
      mail:
        debug: false
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    port: 587
    username: ${gmailSenderLogin}
    password: ${gmailPasswordSMTP}


server:
  port: 8081
  servlet:
    context-path: /notification-service
  error:
    whitelabel:
      enabled: false
    include-message: always

logging:
  level:
    root: info
