spring:
  application:
    name: notification-service

  mail:
    properties:
      mail:
        debug: false
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    port: 587
    username: ${gmailSenderLogin}
    password: ${gmailPasswordSMTP}

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "group-1"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8081
  servlet:
    context-path: /notification-service
  error:
    whitelabel:
      enabled: false
    include-message: always

logging:
  level:
    root: info
