spring:
  application:
    name: notification-service

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    port: 587
    username: ${gmailSenderLogin}
    password: ${gmailPasswordSMTP}
