server:
  port: 8082
  servlet:
    context-path: /notification-service
spring:
  application:
    name: notification-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://localhost:8888
